version: "3.9"

networks:
  ideiasia:
    external: true

services:
  conexao-app:
    image: antonioferrao/agnus-ajustar-intancias:v1.5.12
    networks:
      - ideiasia
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: production
      PORT: 3000
      # Banco de dados externo (valores reais)
      DB_HOST: srv1074.hstgr.io
      DB_USER: u514763314_instancias
      DB_PASSWORD: Acesso@2025AAAAA
      DB_DATABASE: u514763314_instancias
      DB_PORT: "3306"
      # JWT_SECRET removido da stack conforme solicitado
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || wget -qO- http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=ideaisia"
        # === Serviço apontando para a porta interna do container ===
        - "traefik.http.services.conexao.loadbalancer.server.port=3000"
        
        # === Router principal (HTTPS) ===
        - "traefik.http.routers.conexao.rule=Host(`conexao.webferraogroup.com.br`)"
        - "traefik.http.routers.conexao.entrypoints=websecure"
        - "traefik.http.routers.conexao.tls=true"
        - "traefik.http.routers.conexao.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.conexao.service=conexao"

        # === Redirect HTTP -> HTTPS ===
        - "traefik.http.middlewares.conexao-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.conexao-http.rule=Host(`conexao.webferraogroup.com.br`)"
        - "traefik.http.routers.conexao-http.entrypoints=web"
        - "traefik.http.routers.conexao-http.middlewares=conexao-https-redirect"
        - "traefik.http.routers.conexao-http.service=conexao"
