version: "3.9"

networks:
  ideiasia:
    external: true

services:
  conexao-app:
    image: ghcr.io/antonioferrao-hub/agnus_ajustar_intancias:v1.4
    networks:
      - ideiasia
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: production
      PORT: 3000
      # Banco de dados externo (defina no Portainer ou compose env)
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || wget -qO- http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=ideaisia"
        # === Router principal (HTTPS) ===
        - "traefik.http.routers.conexao.rule=Host(`conexao.webferraogorup.com.br`)"
        - "traefik.http.routers.conexao.entrypoints=websecure"
        - "traefik.http.routers.conexao.tls=true"
        - "traefik.http.routers.conexao.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.conexao.service=conexao"
        # === Service apontando para a porta interna do container ===
        - "traefik.http.services.conexao.loadbalancer.server.port=3000"
        - "traefik.http.services.conexao.loadbalancer.passHostHeader=true"