version: "3.9"

networks:
  ideiasia:
    external: true

services:
  agnus_ajustar_intancias:
    image: docker.io/${DOCKERHUB_USERNAME:-antonioferrao}/agnus_ajustar_intancias:${IMAGE_TAG:-latest}
    networks:
      - ideiasia
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # === Router principal (HTTPS) ===
        - "traefik.http.routers.agnus_ajustar_intancias.rule=Host(`agnus.ideias.dev.br`)"
        - "traefik.http.routers.agnus_ajustar_intancias.entrypoints=websecure"
        - "traefik.http.routers.agnus_ajustar_intancias.tls=true"
        - "traefik.http.routers.agnus_ajustar_intancias.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.agnus_ajustar_intancias.service=agnus_ajustar_intancias"
        # === Service apontando para a porta interna do container ===
        - "traefik.http.services.agnus_ajustar_intancias.loadbalancer.server.port=80"
        - "traefik.http.services.agnus_ajustar_intancias.loadbalancer.passHostHeader=true"
